# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google_analytics_ga4: G-XT0PGLRP27

menu:
- {name: 'About Me', folder: 'pages', file: 'about.html'}
- {name: 'Research', folder: 'pages', file: 'research.html'}
- {name: 'Media', folder: 'pages', file: 'media.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
# - {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
# - {icon: 'rss-square', link: 'feed.xml'}
- {icon: 'rss-square', link: 'rss-feed.xml'}
 - {icon: 'linkedin', link: 'https://www.linkedin.com/in/srezayi/'}
 - {icon: 'github', link: 'https://github.com/saedr/'}
 - {icon: 'email', link: 'saedr@uga.edu'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
